# Generated by Django 5.0.1 on 2024-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=3)),
                ('firm', models.CharField(max_length=500)),
                ('blood_group', models.CharField(max_length=5)),
                ('contact_no', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=100)),
            ],
        ),
    ]
