# Generated by Django 5.0.1 on 2024-01-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PandesaraMMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
