# Generated by Django 5.0.1 on 2024-01-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PandesaraMMApp', '0002_alter_record_contact_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
