# Generated by Django 5.0.6 on 2024-07-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PandesaraMMApp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
