# Generated by Django 5.0.6 on 2024-07-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PandesaraMMApp', '0005_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('parivar_no', models.CharField(max_length=10)),
                ('family_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('firm', models.CharField(max_length=500)),
                ('blood_group', models.CharField(max_length=5)),
                ('contact_no', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('fees', models.CharField(max_length=5)),
                ('designation', models.CharField(max_length=100)),
                ('sabhasad_no', models.CharField(max_length=10, null=True)),
                ('reciept_no', models.CharField(max_length=10, null=True)),
                ('reciept_date', models.CharField(max_length=20, null=True)),
                ('kutch_watan', models.CharField(max_length=100)),
            ],
        ),
    ]
